spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations:
    - classpath:mappers/*.xml
    - classpath:org/example/fanzip/*/mapper/*.xml
  type-aliases-package: org.example.fanzip
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: ${JWT_SECRET_KEY}

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: ${KAKAO_REDIRECT_URI}

toss:
  payments:
    client-key: ${TOSS_PAYMENTS_CLIENT_KEY}
    secret-key: ${TOSS_PAYMENTS_SECRET_KEY}

