spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:org/example/fanzip/payment/mapper/*.xml
  type-aliases-package: org.example.fanzip.payment.dto
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret:

kakao:
  client-id:
  redirect-uri:

