name: Fanzip Server CI/CD with Docker

on:
  push:
    branches: [ "feat/cicd" ] # main 브랜치에 push할 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Spring Legacy Build (WAR)
      - name: Spring Legacy Build
        run: ./gradlew clean build -x test

      # Docker Image Build
      - name: Docker Image Build
        run: docker build -t ekhanz/fanzip-server .

      # DockerHub Login
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Docker Hub push
      - name: Docker Hub Push
        run: docker push ekhanz/fanzip-server

      # GET GitHub IP
      - name: Get GitHub IP
        id: ip
        uses: haythem/public-ip@v1.2

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      # Add GitHub IP to AWS Security Group
      - name: Add GitHub IP to AWS
        run: |
          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

      # AWS EC2 Server Connect & Docker Deploy
      - name: AWS EC2 Connection
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          password: ${{ secrets.EC2_PASSWORD }}
          port: ${{ secrets.EC2_SSH_PORT }}
          timeout: 60s
          script: |
            # 기존 컨테이너 정리 (오류 무시)
            sudo docker stop fanzip-server || true
            sudo docker rm fanzip-server || true
            
            # 최신 이미지 다운로드
            sudo docker pull ekhanz/fanzip-server
            
            # 새 컨테이너 실행
            sudo docker run -d \
              --name fanzip-server \
              -p 8080:8080 \
              --restart unless-stopped \
              ekhanz/fanzip-server
            
            # 컨테이너 상태 확인
            sudo docker ps | grep fanzip-server

      # Remove GitHub IP from Security Group
      - name: Remove IP FROM security group
        run: |
          aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32